apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clone-git-repo
spec:
  workspaces:
  - name: main-workspace
  steps:
  - name: git-clone
    image: alpine/git:v2.26.2
    workingDir: /workspace/main-workspace
    script: |
      #!/usr/bin/env sh
      git clone https://github.com/redhat-oraex/tekton-pipeline-demo-app
      chmod 777 -R ./*
      echo "Git clone was a success!"