apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: clone-git-repo
spec:
  params:
  - name: appGitUrl
  workspaces:
  - name: main-workspace
  steps:
  - name: git-checkout
    image: alpine/git:v2.26.2
    workingDir: "$(workspaces.main-workspace.path)"
    script: |
      #!/usr/bin/env sh
      git clone $(params.appGitUrl)
