kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: main-workspace-pvc
  labels:
    pipeline: hello-world-pipeline
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "5Gi"
