apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-world-pipeline
spec:
  workspaces:
  - name: main-workspace
  tasks:
  - name: clone-git-repo-in-pipeline
    taskRef:
      name: clone-git-repo
      kind: Task
    workspaces:
    - name: main-workspace
      workspace: main-workspace
  - name: maven-build-and-nexus-deploy-in-pipeline
    taskRef:
      name: maven-build-and-nexus-deploy
      kind: Task
    workspaces:
    - name: main-workspace
      workspace: main-workspace
    runAfter:
    - clone-git-repo-in-pipeline
  - name: build-and-push-image-in-pipeline
    taskRef:
      name: build-and-push-image
      kind: Task
    workspaces:
    - name: main-workspace
      workspace: main-workspace
    runAfter:
    - maven-build-and-nexus-deploy-in-pipeline