apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-world-pipeline
spec:
  workspaces:
  - name: main-workspace
    persistentVolumeClaim:
      claimName: main-workspace-pvc
  tasks:
  - name: clone-git-repo-pipeline
    taskRef:
      name: clone-git-repo
      kind: Task
  - name: maven-build-pipeline
    taskRef:
      name: maven-build
      kind: Task
    runAfter:
    - clone-git-repo-pipeline
