apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-world-pipeline
spec:
  workspaces:
  - name: main-workspace

  tasks:
  - name: clone-git-repo-pipeline
    taskRef:
      name: clone-git-repo
      kind: Task
    workspaces:
    - name: main-workspace
      workspace: main-workspace

  - name: maven-build-and-nexus-deploy-pipeline
    taskRef:
      name: maven-build-and-nexus-deploy
      kind: Task
    workspaces:
    - name: main-workspace
      workspace: main-workspace
    runAfter:
    - clone-git-repo-pipeline

  - name: build-image-pipeline
    taskRef:
      name: build-image
      kind: Task
    workspaces:
    - name: main-workspace
      workspace: main-workspace
    runAfter:
    - maven-build-and-nexus-deploy-pipeline